# Site settings

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://underlayer.design" # the base hostname & protocol for your site

canonical: "http://underlayer.design"

# Build settings
markdown: kramdown


include: ["_pages"]

exclude: ["node_modules"]

gems:
  - jekyll-sitemap