# Site settings

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://underlayer.design" # the base hostname & protocol for your site

canonical: "http://underlayer.design"

# Build settings
markdown: kramdown


include: ["_pages"]

# port:    4004
# host:    127.0.0.1