# Site settings
description: > # this means to ignore newlines until "baseurl:"
  Underlayer is design and development studio
  that strives to design and develop beautiful,
  easy to use mobile apps and websites for clients like you.

title: Underlayer

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://underlayer.design/" # the base hostname & protocol for your site

canonical: "http://underlayer.design/"

# Build settings
markdown: kramdown


include: ["_pages"]

exclude: ["node_modules", "history.lock", "gulpfile.js", config.yml, "package.json"]

gems:
  - jekyll-sitemap